### 异常机制

![image-20220211144351604](https://www.itbaizhan.com/wiki/imgs/image-20220211144351604.png?v=1.0.0)

![image-20220211144436651](https://www.itbaizhan.com/wiki/imgs/image-20220211144436651.png?v=1.0.0)

![image-20220211144459678](https://www.itbaizhan.com/wiki/imgs/image-20220211144459678.png?v=1.0.0)

#### **导引问题**

> 工作中，程序遇到的情况不可能完美。比如：程序要打开某个文件，这个文件可能不存在或者文件格式不对；程序在运行着，但是内存或硬盘可能满了等等。

> 软件程序在运行过程中，非常可能遇到刚刚提到的这些问题，我们称之为异常，英文是：Exception，意思是例外。遇到这些例外情况，或者叫异常，我们怎么让写的程序做出合理的处理，安全的退出，而不至于程序崩溃呢？我们本章就要讲解这些问题。



如果要拷贝文件，在没有异常机制的情况下，我们需要考虑各种异常情况，伪代码如下：



【示例】伪代码：使用if处理程序中可能出现的各种情况

![image-20220211144655407](https://www.itbaizhan.com/wiki/imgs/image-20220211144655407.png?v=1.0.0)

**这种方式，有两个坏处：**

1. 逻辑代码和错误处理代码放一起！
2. 程序员本身需要考虑的例外情况较复杂，对程序员本身要求较高！



如上情况，如果是用Java的异常机制来处理，对比如下：

![image-20220211144739656](https://www.itbaizhan.com/wiki/imgs/image-20220211144739656.png?v=1.0.0)

> **异常机制本质**
>
> 当程序出现异常，程序安全的退出、处理完后继续执行的机制

#### **异常（Exception）的概念**

异常指程序运行过程中出现的非正常现象，例如除数为零、需要处理的文件不存在、数组下标越界等。

在Java的异常处理机制中，引进了很多用来描述和处理异常的类，称为异常类。异常类定义中包含了该类异常的信息和对异常进行处理的方法。



我们开始看我们的第一个异常对象，并分析一下异常机制是如何工作的。

【示例】异常的分析

```java
public class Test {
  public static void main(String[] args) {
    System.out.println("111");
    int a = 1/0;
    System.out.println("222");
   }
}

```

执行结果如图所示：

![image-20220211144916895](https://www.itbaizhan.com/wiki/imgs/image-20220211144916895.png?v=1.0.0)

根据结果，我们可以看到执行“1/0”时发生了异常，程序终止了，没有执行后面的打印“222”的动作。

如果我们使用try-catch来处理，程序遇到异常可以正常的处理，处理完成后，程序继续往下执行：

```java
public class Test {
  public static void main(String[] args) {
    System.out.println("111");
    try {
      int a = 1/0;
     } catch (Exception e) {
      e.printStackTrace();
     }
    System.out.println("222");
   }
}

```

执行结果如下：

![image-20220211145103666](https://www.itbaizhan.com/wiki/imgs/image-20220211145103666.png?v=1.0.0)

程序在执行“1/0”仍然遇到异常，然后进行try-catch处理。处理完毕后，程序继续往下执行，打印了“222”内容。



**Java是采用面向对象的方式来处理异常的。处理过程：**

- **抛出异常：**在执行一个方法时，如果发生异常，则这个方法生成**代表该异常的一个对象**，停止当前执行路径，并把异常对象提交给JRE。
- **捕获异常：**JRE得到该异常后，寻找相应的代码来处理该异常。JRE在方法的调用栈中查找，从生成异常的方法开始回溯，直到找到相应的异常处理代码为止。



#### **异常分类**

Java中定义了很多异常类，这些类对应了各种各样可能出现的异常事件，所有异常对象都是派生于`Throwable`类的一个实例。如果内置的异常类不能够满足需要，还可以创建自己的异常类。

Java对异常进行了分类，不同类型的异常分别用不同的Java类表示，所有异常的根类为`java.lang.Throwable`，`Throwable`下面又派生了两个子类：`Error`和`Exception`。Java异常类的层次结构如图所示：

![image-20220211145204956](https://www.itbaizhan.com/wiki/imgs/image-20220211145204956.png?v=1.0.0)

**Error**

Error是程序无法处理的错误，表示运行应用程序中较严重问题。大多数错误与代码编写者执行的操作无关，而表示代码运行时 JVM（Java 虚拟机）出现的问题。例如，Java虚拟机运行错误（Virtual MachineError），当 JVM 不再有继续执行操作所需的内存资源时，将出现 OutOfMemoryError。这些异常发生时，Java虚拟机（JVM）一般会选择线程终止。

Error表明系统JVM已经处于不可恢复的崩溃状态中。

![image-20220211145306560](https://www.itbaizhan.com/wiki/imgs/image-20220211145306560.png?v=1.0.0)

**java.lang包中Error的类**

> **Error与Exception的区别**
>
> - 我开着车走在路上，一头猪冲在路中间，我刹车。这叫一个异常。
> - 我开着车在路上，发动机坏了，我停车，这叫错误。系统处于不可恢复的崩溃状态。发动机什么时候坏？我们普通司机能管吗？不能。发动机什么时候坏是汽车厂发动机制造商的事。

**Exception**

Exception是程序本身能够处理的异常。

Exception类是所有异常类的父类，其子类对应了各种各样可能出现的异常事件。 通常Java的异常可分为：

1. RuntimeException 运行时异常
2. CheckedException 已检查异常

![image-20220211145719699](https://www.itbaizhan.com/wiki/imgs/image-20220211145719699.png?v=1.0.0)

**RuntimeException运行时异常**

派生于RuntimeException的异常，如被 0 除、数组下标越界、空指针等，其产生比较频繁，处理麻烦，如果显式的声明或捕获将会对程序可读性和运行效率影响很大。因此由系统自动检测并将它们交给缺省的异常处理程序。

编译器不处理RuntimeException, 程序员需要增加“逻辑处理来避免这些异常”。

【示例】ArithmeticException异常：试图除以0

```java
public class Test3 {
    public static void main(String[ ] args) {
        int b=0;
        System.out.println(1/b);
    }
}

```

执行结果如图所示：

![image-20220211145923894](https://www.itbaizhan.com/wiki/imgs/image-20220211145923894.png)

**解决如上异常需要修改代码：**

```java
public class Test3 {
    public static void main(String[ ] args) {
        int b=0;
        if(b!=0){
            System.out.println(1/b);
        }
    }
}

```



【示例】NullPointerException异常

```java
public class Test4 {
    public static void main(String[ ] args) {
        String str=null;
        System.out.println(str.charAt(0));
    }
}

```

执行结果如图所示：

![image-20220211150346438](https://www.itbaizhan.com/wiki/imgs/image-20220211150346438.png)

解决空指针异常，通常是增加非空判断：

```java
public class Test4 {
    public static void main(String[ ] args) {
        String str=null;
        if(str!=null){
            System.out.println(str.charAt(0));
        }
    }
}

```

【示例】ClassCastException异常

```java
class Animal{
    
}
class Dog extends Animal{
    
}
class Cat extends Animal{
    
}
public class Test5 {
    public static void main(String[ ] args) {
        Animal a=new Dog();
        Cat c=(Cat)a;
    }
}

```

执行结果如图所示：

![image-20220211150508728](https://www.itbaizhan.com/wiki/imgs/image-20220211150508728.png)

解决ClassCastException的典型方式：

```java
public class Test5 {
    public static void main(String[ ] args) {
        Animal a = new Dog();
        if (a instanceof Cat) {
            Cat c = (Cat) a;
        }
    }
}

```

【示例】ArrayIndexOutOfBoundsException异常

```java
public class Test6 {
    public static void main(String[ ] args) {
        int[ ] arr = new int[5];
        System.out.println(arr[5]);
    }
}

```

执行结果如图所示：

![image-20220211150638023](https://www.itbaizhan.com/wiki/imgs/image-20220211150638023.png)

解决数组索引越界异常的方式，增加关于边界的判断：

```java
public class Test6 {
    public static void main(String[ ] args) {
        int[ ] arr = new int[5];
        int a = 5;
        if (a < arr.length) {
            System.out.println(arr[a]);
        }
    }
}

```

【示例】NumberFormatException异常

```java
public class Test7 {
    public static void main(String[ ] args) {
        String str = "1234abcf";
        System.out.println(Integer.parseInt(str));
    }
}

```

执行结果如图所示：

![image-20220211150828030](https://www.itbaizhan.com/wiki/imgs/image-20220211150828030.png)

数字格式化异常的解决，可以引入正则表达式判断是否为数字：

```java
import java.util.regex.Matcher;
import java.util.regex.Pattern;


public class Test7 {
    public static void main(String[ ] args) {
        String str = "1234abcf";
        Pattern p = Pattern.compile("^\\d+$");
        Matcher m = p.matcher(str);
        if (m.matches()) { // 如果str匹配代表数字的正则表达式,才会转换
            System.out.println(Integer.parseInt(str));
        }
    }
}

```

**实时效果反馈**

**1. 如下关于异常机制的说法，==错误==的是:**

A 异常机制是：当程序出现异常，程序安全的退出、处理完后继续执行的机制

B Java是采用面向对象的方式来处理异常的

C 抛出异常：执行一个方法时，如果发生异常，则这个方法生成代表该异常的一个对象，停止当前执行路径，并把异常对象提交给JRE

D ==抛出异常：执行一个方法时，如果发生异常，则找到以前生成的代表这个异常的对象，停止当前执行路径，并把异常对象提交给JRE==

**2. 如下关于异常的分类，==错误==的是:**

A 所有异常的根类为`java.lang.Throwable`，`Throwable`下面又派生了两个子类：`Error`和`Exception`

B ==`Error`是程序无法处理的错误，表示运行应用程序中较严重问题，需要`try-catch`处理。==

C `RuntimeException`异常，其产生比较频繁。编译器不处理`RuntimeException`, 程序员需要增加“逻辑处理来避免这些异常”。

D `CheckedException`异常，是需要编译器处理的，我们使用`try-catch`结构来处理。

**答案**

1=>D 2=>B

### **`CheckedException`已检查异常**

![image-20220211150948327](https://www.itbaizhan.com/wiki/imgs/image-20220211150948327.png?v=1.0.0)

`CheckedException`异常在编译时就必须处理，否则无法通过编译。如图所示。

![image-20220211151031519](https://www.itbaizhan.com/wiki/imgs/image-20220211151031519.png?v=1.0.0)

`CheckedException`异常的处理方式有两种：

1. 使用`try/catch`捕获异常
2. 使用`throws`声明异常。

**实时效果反馈**

**1. 如下关于`checkedException`的说法，错误的是:**

A `checkedException`需要编译时处理，否则无法通过编译。

B `checkedException`可以在编译时处理，也可以在运行时处理。

C `checkedException`可以使用`try-catch`捕获异常处理。

D `checkedException`可以使用`throws`声明异常。

**答案**

1=>B

### **异常的处理方式之一：捕获异常**

![image-20220211151121738](https://www.itbaizhan.com/wiki/imgs/image-20220211151121738.png?v=1.0.0)

**try：**

`try`语句指定了一段代码，该段代码就是异常捕获并处理的范围。在执行过程中，当任意一条语句产生异常时，就会跳过该条语句中后面的代码。代码中可能会产生并抛出一种或几种类型的异常对象，它后面的`catch`语句要分别对这些异常做相应的处理。

一个try语句必须带有至少一个`catch`语句块或一个`finally`语句块。

> **注意事项**
>
> - 当异常处理的代码执行结束以后，不会回到`try`语句去执行尚未执行的代码。

**catch：**

1. 每个`try`语句块可以伴随一个或多个`catch`语句，用于处理可能产生的不同类型的异常对象。

2. `catch`捕获异常时的捕获顺序：

   如果异常类之间有继承关系，先捕获子类异常再捕获父类异常。

**finally：**

1. 不管是否发生了异常，都必须要执行。
2. 通常在`finally`中关闭已打开的资源，比如：关闭文件流、释放数据库连接等。



**`try-catch-finally`语句块的执行过程详细分析：**

1. 程序首先执行可能发生异常的`try`语句块。
2. 如果`try`语句没有出现异常则执行完后跳至`finally`语句块执行；
3. 如果`try`语句出现异常，则中断执行并根据发生的异常类型跳至相应的`catch`语句块执行处理。
4. `catch`语句块可以有多个，分别捕获不同类型的异常。
5. `catch`语句块执行完后程序会继续执行`finally`语句块。
6. `finally`语句是可选的，如果有的话，则不管是否发生异常，`finally`语句都会被执行。

【示例】异常处理的典型代码(捕获异常)

```java
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
public class Test8 {
    public static void main(String[ ] args) {
        FileReader reader = null;
        try {
            reader = new FileReader("d:/a.txt");
            char c = (char) reader.read();
            char c2 = (char) reader.read();
            System.out.println("" + c + c2);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (reader != null) {
                    reader.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
```

> **常用开发环境中，自动增加try-catch代码块的快捷键：**
>
> 1. 将需要处理异常的代码选中。
> 2. IDEA中，使用：ctrl+alt+t
> 3. eclipse中，使用：ctrl+shift+z

**实时效果反馈**

**1. 如下关于`try-catch-finally`结构的说法，错误的是:**

A `try`语句指定了一段代码，该段代码就是异常捕获并处理的范围。

B 若碰到异常，当`catch`执行结束后，会回到`try`语句去执行尚未执行的代码

C 每个`try`语句块可以伴随一个或多个`catch`语句

D `finally`块：不管是否发生了异常，都必须要执行。

**答案**

1=>B

 

### 异常的处理方式之二：声明异常（throws子句）

![image-20220211151442602](https://www.itbaizhan.com/wiki/imgs/image-20220211151442602.png?v=1.0.0)

1. CheckedException产生时，不一定立刻处理它，可以把异常throws，由调用者处理。
2. 一个方法抛出多个已检查异常，就必须在方法的首部列出所有的异常。

【示例】异常处理的典型代码（声明异常抛出throws）

```java
package com.bjsxt;


import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;


public class Test9 {
  public static void main(String[ ] args) {
    try {
      readFile("joke.txt");
     } catch (FileNotFoundException e) {
      System.out.println("所需文件不存在！");
     } catch (IOException e) {
      System.out.println("文件读写错误！");
     }
   }
  public static void readFile(String fileName) throws FileNotFoundException,
      IOException {
    FileReader in = new FileReader(fileName);
    int tem = 0;
    try {
      tem = in.read();
      while (tem != -1) {
        System.out.print((char) tem);
        tem = in.read();
       }
     } finally {
      if(in!=null) {
        in.close();
       }
     }
   }
}

```

> **注意事项**
>
> 🟤方法重写中声明异常原则：子类重写父类方法时，如果父类方法有声明异常，那么子类声明的异常范围不能超过父类声明的范围。

### **JDK新特性_**

**try-with-resource自动关闭AutoClosable接口的资源**

> JAVA中，JVM的垃圾回收机制可以对内部资源实现自动回收，给开发者带来了极大的便利。
>
> 但是JVM对外部资源(调用了底层操作系统的资源)的引用却无法自动回收，例如数据库连接，网络连接以及输入输出IO流等。这些连接就需要我们手动去关闭，不然会导致外部资源泄露，连接池溢出以及文件被异常占用等。

JDK7之后，新增了“try-with-resource”。它可以自动关闭实现了`AutoClosable`接口的类，实现类需要实现`close()`方法。

> ”try-with-resources “ 将`try-catch-finally` 简化为`try-catch`，这其实是一种语法糖，在编译时仍然会进行转化为`try-catch-finally` 语句。

```java
package com.bjsxt;


import java.io.FileReader;
public class Test8 {
  public static void main(String[ ] args) {
    try(FileReader reader = new FileReader("d:/a.txt");) {
      char c = (char) reader.read();
      char c2 = (char) reader.read();
      System.out.println("" + c + c2);
     } catch (Exception e) {
      e.printStackTrace();
     }
   }
}

```

**实时效果反馈**

**1. 如下关于`try-with-resource`，说法错误的是:**

A `try-with-resource`可自动关闭实现了`AutoClosable`接口的类，实现类需要实现`close()`方法

B `try-with-resource` 编译后形成的真正代码完全和`try-catch-finally` 不一样

C 在编译时仍然会将`try-with-resource`转化为`try-catch-finally` 语句

D `try-with-resource`是一种语法糖

**答案**

1=>B

### **自定义异常**

- 在程序中，可能会遇到JDK提供的任何标准异常类都无法充分描述清楚我们想要表达的问题，这种情况下可以创建自己的异常类，即自定义异常类。
- 自定义异常类只需从Exception类或者它的子类派生一个子类即可。
- 自定义异常类如果继承Exception类，则为CheckedException异常，必须对其进行处理；如果不想处理，可以让自定义异常类继承运行时异常RuntimeException类。
- 习惯上，自定义异常类应该包含2个构造器：一个是默认的构造器，另一个是带有详细信息的构造器。

【示例】自定义异常类

```java
/**IllegalAgeException：非法年龄异常，继承Exception类*/
public class IllegalAgeException extends Exception {
    //默认构造器
    public IllegalAgeException() {
    
    }
    //带有详细信息的构造器，信息存储在message中
    public IllegalAgeException(String message) {
        super(message);
    }
}

```

【示例】自定义异常类的使用

```java
class Person {
    private String name;
    private int age;


    public void setName(String name) {
        this.name = name;
    }


    public void setAge(int age) throws IllegalAgeException {
        if (age < 0) {
            throw new IllegalAgeException("人的年龄不应该为负数");
     }
        this.age = age;
    }


    public String toString() {
        return "name is " + name + " and age is " + age;
    }
}


public class TestMyException {
    public static void main(String[ ] args) {
        Person p = new Person();
        try {
            p.setName("Lincoln");
            p.setAge(-1);
        } catch (IllegalAgeException e) {
            e.printStackTrace();
        }
        System.out.println(p);
    }
}

```

执行结果如图所示：

![image-20220211152011764](https://www.itbaizhan.com/wiki/imgs/image-20220211152011764.png)

> **使用异常机制的建议**
>
> - 要避免使用异常处理代替错误处理，这样会降低程序的清晰性，并且效率低下。
> - 处理异常不可以代替简单测试---只在异常情况下使用异常机制。
> - 不要进行小粒度的异常处理---应该将整个任务包装在一个try语句块中。
> - 异常往往在高层处理(先了解！后面做项目会说！) 。

### **如何利用百度解决异常问题**

![image-20220211152326352](https://www.itbaizhan.com/wiki/imgs/image-20220211152326352.png?v=1.0.0)

正常学习和开发中，我们经常会遇到各种异常。遇到异常时，需要遵循下面四步来解决：

1. 细心查看异常信息，确定异常种类和相关Java代码行号
2. 确定上下文相关的一些关键词信息（疑难问题，需要）。拷贝异常信息到百度，查看相关帖子，寻找解决思路；
3. 前两步无法搞定，再问同学/老师或同事；
4. 前三步无法搞定，请示领导。



很多同学碰到异常一下就慌了，立刻开始请教别人搬救兵，殊不知这样做有两大坏处。第一、太不尊重别人，把别人当苦力。第二、失去提高自我的机会，自己解决一个异常，就意味着有能力解决一类异常。解决一类异常能大大提高自身能力。

不要怕花时间在解决问题上，不要觉得解决问题是耽误时间。解决问题的过程中，本身你也在思考。



**百度超级搜索：**

百度/Google搜索用好的关键是：关键词的确认，正确的提问。

1. 寻找问题本身的关键词（名词）
2. 寻找问题上下文的关键词（名词）
3. 尽量细致的描述问题，开始搜索
4. 如果没找到，慢慢减少关键词，扩大搜索范围。



**实时效果反馈**

**1. 编程中遇到异常，错误的做法是:**

A 定位错误，稳住心态。问题是提高的阶梯！自己解决一个问题，经验提高一点

B 寻找问题本身的关键词，进行百度

C 查看较多相关帖子，整理思路

D 碰到错误，自己不解决，先问老师，让老师直接解决掉，省时间

**答案**

1=>D

###  **IDEA调试debug**

<img src="https://www.itbaizhan.com/wiki/imgs/image-20220211152845199.png?v=1.0.0" alt="image-20220211152845199" style="zoom:50%;" />

调试的核心是断点。程序执行到断点时，暂时挂起，停止执行。就像看视频按下停止一样，我们可以详细的观看停止处的每一个细节。

#### **断点breakpoint**

程序运行到此处，暂时挂起，停止执行。我们可以详细在此时观察程序的运行情况，方便做出进一步的判断。



1. 设置断点：
   - 在行号后面单击即可增加断点

![image-20220211153547606](https://www.itbaizhan.com/wiki/imgs/image-20220211153547606.png?v=1.0.0)

- 在断点上再单击即可取消断点

#### **进入调试视图**

我们通过如下三种方式都可以进入调试视图：

1. 单击工具栏上的按钮：![image-20220211153837315](https://www.itbaizhan.com/wiki/imgs/image-20220211153837315.png?v=1.0.0)

2. 右键单击编辑区，点击：debug

   进入调试视图后，布局如下：

![image-20220211153953613](https://www.itbaizhan.com/wiki/imgs/image-20220211153953613.png?v=1.0.0)

左侧为“浏览帧”：

调试器列出断点处，当前线程正在运行的方法，每个方法对应一个“栈帧”。最上面的是当前断点所处的方法。



变量值观察区：

调试器列出了断点处所在方法相关的变量值。我们可以通过它，查看变量的值的变化。

#### **调试操作区**

![image-20220211154049064](https://www.itbaizhan.com/wiki/imgs/image-20220211154049064.png?v=1.0.0)

我们通过上图中的按钮进行调试操作，它们的含义如下：

![image-20220211154233108](https://www.itbaizhan.com/wiki/imgs/image-20220211154233108.png?v=1.0.0)